region                         = "us-east-1"
vpc_cidr                       = "10.0.0.0/16"
cluster_name                   = "devops-time-service-eks"
kubernetes_version             = "1.30"
availability_zones             = ["us-east-1a", "us-east-1b"]
private_subnet_cidrs           = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_cidrs            = ["10.0.101.0/24", "10.0.102.0/24"]
node_instance_types            = ["m6a.large"]
node_desired_size              = 2
node_min_size                  = 2
node_max_size                  = 2
enable_nat_gateway             = true
single_nat_gateway             = true
cluster_endpoint_public_access = true
